# Generated by Django 2.1.3 on 2019-03-12 13:07

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.NullBooleanField(default=None)),
                ('start', models.PositiveIntegerField()),
                ('word_shift', models.PositiveSmallIntegerField()),
                ('word_len', models.PositiveSmallIntegerField()),
                ('end_shift', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_info', models.CharField(help_text='Type by format: <first_name>$<last_name>$<bdate>$<edate>', max_length=173)),
                ('book_title', models.CharField(max_length=200)),
                ('book_genre', models.CharField(max_length=50)),
                ('book_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/alex/code/git/Catal/WebSite/catalog/temp/books/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('book_extras', models.TextField(help_text='Type by format: <language>$<summary>$<isbn>', max_length=1065)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.NullBooleanField(default=None)),
                ('inserter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_temp', related_query_name='ins_tmp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book_title'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.NullBooleanField(default=None)),
                ('name', models.CharField(max_length=30)),
                ('occurs_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', related_query_name='symb', to='temp.Pack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='addresses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='adr', to='temp.Symbol'),
        ),
    ]
