# Generated by Django 2.1.3 on 2019-04-23 07:00

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_auto_20190420_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='book_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/alex/code/git/Catal/WebSite/catalog/temp/books/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
