const constants = {
    MENU_INIT: 'MENU_INIT',
    SELECT_SYMBOL: 'SELECT_SYMBOL',

    UPDATE_PAGE_REQUEST: 'UPDATE_PAGE_REQUEST',
    UPDATE_PAGE_SUCCESS: 'UPDATE_PAGE_SUCCESS',
    UPDATE_PAGE_FAILURE: 'UPDATE_PAGE_FAILURE',
}

export default constants;
