const constants = {
    MENU_INIT: 'MENU_INIT',
    SELECT_SYMBOL: 'SELECT_SYMBOL',
    SELECT_TEXT_COORDINATES: 'SELECT_TEXT_COORDINATES',

    UPDATE_PAGE_REQUEST: 'UPDATE_PAGE_REQUEST',
    UPDATE_PAGE_SUCCESS: 'UPDATE_PAGE_SUCCESS',
    UPDATE_PAGE_FAILURE: 'UPDATE_PAGE_FAILURE',

    SYMBOL_ADDITION: 'SYMBOL_ADDITION',

    SYMBOL_SAVE_REQUEST: 'SYMBOL_SAVE_REQUEST',
    SYMBOL_SAVE_SUCCESS: 'SYMBOL_SAVE_SUCCESS',
    SYMBOL_SAVE_FAILURE: 'SYMBOL_SAVE_FAILURE',
}

export default constants;
