# Generated by Django 2.1.3 on 2019-04-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symboldescription',
            name='symbol',
        ),
        migrations.AddField(
            model_name='symbol',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbols', to='catalog.SymbolDescription'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='existence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='adr', to='catalog.Existences'),
        ),
    ]
