# Generated by Django 2.1.3 on 2019-04-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190403_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Location',
        ),
    ]
