# Generated by Django 2.1.3 on 2019-04-04 23:17

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190403_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existence',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existence_set', related_query_name='ex_set', to='catalog.Book'),
        ),
        migrations.AlterField(
            model_name='existence',
            name='inserter',
            field=models.ForeignKey(on_delete=models.SET(catalog.models.get_sentinel_user), related_name='inserted', related_query_name='insert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='existence',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existences', related_query_name='exists', to='catalog.Symbol'),
        ),
        migrations.AlterField(
            model_name='location',
            name='existence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='located', to='catalog.Existence'),
        ),
    ]
