# Generated by Django 2.1.3 on 2019-04-20 18:27

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190405_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload your text of book in one single file here', storage=django.core.files.storage.FileSystemStorage(location='/home/vladislav/projects/WebSite/WebSite/catalog/books/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
        migrations.DeleteModel(
            name='SymbolDescription',
        ),
    ]
