# Generated by Django 2.1.3 on 2019-04-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190420_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='catalog.Symbol')),
            ],
        ),
    ]
