# Generated by Django 2.1.3 on 2019-04-23 07:00

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_symboldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload your text of book in one single file here', storage=django.core.files.storage.FileSystemStorage(location='/home/alex/code/git/Catal/WebSite/catalog/books/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
