# Generated by Django 2.1.3 on 2019-06-23 13:54

import accounts.utils
from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_auto_20190621_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.BooleanField(default=False)),
                ('date_checked', models.DateTimeField(default=None, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('inserter', models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_contexts', related_query_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.BooleanField(default=False)),
                ('date_checked', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('inserter', models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_contexttypes', related_query_name='contexttypes', to=settings.AUTH_USER_MODEL)),
                ('who_checked', models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_contexttypes', related_query_name='contexttypes_checked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='symboldescription',
            name='symbol',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['start', 'word_shift', 'word_len']},
        ),
        migrations.AddField(
            model_name='author',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_authors', related_query_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_authors', related_query_name='authors_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_books', related_query_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_books', related_query_name='books_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='genre',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_genres', related_query_name='genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_genres', related_query_name='genres_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='language',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_languages', related_query_name='languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_languages', related_query_name='languages_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_locations', related_query_name='locations_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symbol',
            name='date_checked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='symbol',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_symbols', related_query_name='symbols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symbol',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_symbols', related_query_name='symbols_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload your text of book in one single file here', storage=django.core.files.storage.FileSystemStorage(location='/home/vladislav/projects/WebSite/WebSite/catalog/books/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 length character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='location',
            name='inserter',
            field=models.ForeignKey(default=accounts.utils.default_user, on_delete=models.SET(accounts.utils.dummy_deleted_user), related_name='added_locations', related_query_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SymbolDescription',
        ),
        migrations.AddField(
            model_name='context',
            name='locations',
            field=models.ManyToManyField(to='catalog.Location'),
        ),
        migrations.AddField(
            model_name='context',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ContextType'),
        ),
        migrations.AddField(
            model_name='context',
            name='who_checked',
            field=models.ForeignKey(default=None, null=True, on_delete=accounts.utils.default_user, related_name='checked_contexts', related_query_name='contexts_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='contexts',
            field=models.ManyToManyField(to='catalog.Context'),
        ),
    ]
