# Generated by Django 2.1.3 on 2019-06-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190623_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='locations',
        ),
    ]
