# Generated by Django 2.1.3 on 2019-10-06 18:04

import accounts.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_context_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_authors', related_query_name='authors_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_books', related_query_name='books_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='context',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_contexts', related_query_name='contexts_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contexttype',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contexttype',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_contexttypes', related_query_name='contexttypes_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_genres', related_query_name='genres_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_languages', related_query_name='languages_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_locations', related_query_name='locations_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=accounts.utils.default_user, related_name='checked_symbols', related_query_name='symbols_checked', to=settings.AUTH_USER_MODEL),
        ),
    ]
